- name: Set Up CloudWatch on a EC2 Instance
  hosts: all
  vars:
    - cloudwatch_config_location: /opt/aws/amazon-cloudwatch-agent/config.json
  tasks:
    - name: Create .aws Directory
      file:
        path: ~/.aws
        state: directory
        mode: '0755'
    
    - name: Copy CloudWatch Agent config
      copy:
        src: "./.aws/cloudwatch-agent-config.json"
        dest: "{{ cloudwatch_config_location }}"
      become: yes

    - name: Yum Update
      yum:
        update_only: yes

    - name: Install Collectd
      command: amazon-linux-extras install collectd -y
      become: yes

    - name: Install CloudWatch Agent
      yum:
        name: amazon-cloudwatch-agent
        state: latest
      become: yes
    
    - name: Start CloudWatch Agent
      command: "sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:{{ cloudwatch_config_location }}"
    