image:
  pullPolicy: Always
  tag: latest

ingress:
  annotations:
    # kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    # traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  enabled: true
  hosts:
    - grafana.termite.cloud
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.termite.cloud