image:
  pullPolicy: Always
  tag: latest

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  enabled: true
  hosts:
    - grafana.termite.cloud
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.termite.cloud